services:
  - type: web
    name: univers-libre
    runtime: ruby
    buildCommand: chmod +x bin/render-build.sh && ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
